config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'

  devise_for :users
  get 'user/index'
  root 'user#index'
  resources :users
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord	
	mount_uploader :image, ImageUploader
	belongs_to :user

	def previous
		user.articles.where("id < ?", self.id).last
	end

	def next
		user.articles.where("id > ?", id).first
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def after_sign_out_path_for(resource_or_scope)
	new_user_session_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# before_action :set_user, only: [:new, :create]
  def index
  	@articles = current_user.articles
  end

  def new
  	@article = current_user.articles.new
  end

  def create

  	@article = current_user.articles
  	@article = @article.new(paramaters)
    if @article.save
     redirect_to article_path(id:@article.id)
     else
      render 'new'
    end
  end
  def edit 
  	 @article = current_user.articles.find(params[:id])
  end
  def show
  	@article = current_user.articles.find(params[:id])
  end
  def update
     @article = current_user.articles.find(params[:id])
     @article.update(paramaters)
     redirect_to article_path(id:@article.id)
  end

  private
  def paramaters
    params.require(:article).permit(:description, :image)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  	@users = User.all
  end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/_articleform.html.erb
<%= form_for @article, html: { multipart: true } do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
 
      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h3 style="text-align:center;"> Articles#edit </h3>
<%= render partial: "articleform" %>

app/views/articles/index.html.erb
<h3 style="text-align:center;"> Articles </h3>

	<% @articles.each do |article| %>
	<% if article.persisted? %>
	<p>
  <strong>Description:</strong>
  <%= article.description %>
</p>
 <p>
  <strong>Image:</strong>
  <%= image_tag article.image_url.to_s   %>
</p>
<%=link_to 'show',article_url(id:article.id)%></br>
<%end%><%end%>

app/views/articles/new.html.erb
<h3 style="text-align:center;"> Articles#new </h3>
<%= render partial: "articleform" %>

app/views/articles/show.html.erb
<h3 style="text-align:center;"> Articles of the user</h3>
<p id="notice"><%= notice %></p>
 <div style="text-align:center;">
<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>
 
<p>
	<% if @article.previous.present? %>
  <%= link_to "<", @article.previous, :html_options => {:accesskey => "LEFT ARROW"} %>
  <%end%>
  <%= image_tag @article.image.thumb.url unless @article.image.blank? %>
 	<% if @article.next.present? %>
 <%= link_to ">", @article.next, :html_options => {:accesskey => "LEFT ARROW"} %>
 <%end%>
</p>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', new_article_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserLogin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/index.html.erb
<% if user_signed_in? %>
	<% if current_user.articles.present? %>
	<%= link_to 'view article',article_url(current_user.articles.first) %>
	<% end %>
	<%= link_to 'logout', destroy_user_session_url, method: :delete %>
	<%= link_to 'Create Article', new_article_path %>
<% else %>
	<%= link_to 'signin', new_user_session_url %>
	<%= link_to 'signup', new_user_registration_url%>
<% end %>